ban-car/models/Destinatarios.php
<?php

namespace app\models;

use yii\db\ActiveQuery;
use yii\db\ActiveRecord;


/**
 * This is the model class for table "destinatarios".
 *
 * @property int $ID_DES
 * @property int $DNI
 * @property string $Nombre_RazonSocial
 * @property double $Cuit_Cuil
 * @property int $ID_Tipo
 * @property int $ID_Provincia
 * @property int $ID_Localidad
 * @property int $Direccion
 * @property string $Email
 * @property CartasDocumento[] $cartasdocumento
 * @property Provincias $provinciaDES
 * @property Localidades $localidadDES
 * @property TipoDestinatario $tipoDES
 */
class Destinatarios extends ActiveRecord
{   const SCENARIO_UPDATE = "update";
    const SCENARIO_UPDATE_LOCALIDAD = "update_localidad";
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'destinatarios';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['DNI','Nombre_RazonSocial', 'Cuit_Cuil', 'Tipo_documento', 'Sucursal','Cuenta','Grupo','Subgrupo','Tipo_cuenta','Direccion','ID_Provincia','Codigo_pais','ID_Provincia','Tipo_domicilio'], 'required'],
            [['DNI','Tipo_documento','Fecha_Nacimiento','Cuit_Cuil','Telefono', 'Celular','Cod_postal','Estado_civil','Cod_actividad','Sucursal','Cuenta','ID_Provincia','Codigo_pais','ID_Localidad','Tipo_domicilio'], 'integer'],
            ['Email','email','message'=>'Formato no valido'],
            [['ID_Localidad'], 'required', 'when'=> function($model){
                    return isset($model->ID_Provincia);
            }],
            [['Nombre_RazonSocial','Direccion'], 'string', 'max' => 100],
            [['Subgrupo','Grupo','Tipo_cuenta','Sexo','Ciudadania'], 'string', 'max' => 50],
            [['Codigo_pais'], 'exist', 'skipOnError' => true, 'targetClass' => Pais::className(), 'targetAttribute' => ['Codigo_pais' => 'Cod_Pais']],
            [['ID_Provincia'], 'exist', 'skipOnError' => true, 'targetClass' => Provincias::className(), 'targetAttribute' => ['ID_Provincia' => 'id']],
            [['ID_Localidad'], 'exist', 'skipOnError' => true, 'targetClass' => Localidades::className(), 'targetAttribute' => ['ID_Localidad' => 'id']],
        ];
    }
    
     public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios[self::SCENARIO_UPDATE_LOCALIDAD] = ['Nombre_RazonSocial', 'Sucursal','Cuenta','Grupo','Tipo_cuenta','Direccion','ID_Provincia','Codigo_pais','ID_Provincia','Tipo_domicilio','ID_Localidad'];
        $scenarios[self::SCENARIO_UPDATE] = ['Nombre_RazonSocial', 'Sucursal','Cuenta','Grupo','Tipo_cuenta','Direccion','ID_Provincia','Codigo_pais','ID_Provincia','Tipo_domicilio'];
        return $scenarios;
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'DNI'                              =>'Numero de Documento',
            'Tipo_documento'                   =>'Tipo de Documento',
            'Nombre_RazonSocial'               =>'Nombre',
            'Cuit_Cuil'                        =>'Cuil/Cuit',
            'Sexo'                             =>'Sexo',
            'Fecha_Nacimiento'                 =>'Fecha de Nacimiento',
            'Ciudadania'                       =>'Ciudadania',
            'Telefono'                         =>'Telefono',
            'Celular'                          =>'Celular',
            'Cod_postal'                       =>'Codigo Postal',
            'Email'                            =>'Email',
            'Estado_civil'                     =>'Estado Civil',
            'Cod_actividad'                    =>'Codigo de Actividad',
            'Direccion'                        =>'Direccion', 
            'Sucursal'                         =>'Sucursal',
            'Cuenta'                           =>'Cuenta',
            'Grupo'                            =>'Grupo',
            'Subgrupo'                         =>'Subgrupo',
            'Tipo_cuenta'                      =>'Tipo de Cuenta',
            'Codigo_pais'                      =>'Codigo de Pais',
            'ID_Provincia'                     =>'Provincia',
            'ID_Localidad'                     =>'Localidad'
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getCartasdocumento()
    {
        return $this->hasMany(CartasDocumento::className(), ['destinatarios' => 'Cuit_cuil']);
    }

    public function getPais()
    {
        return $this->hasOne(Pais::className(), ['Cod_Pais' => 'Codigo_pais']);
    }
    
    public function getProvincia()
    {
        return $this->hasOne(Provincias::className(), ['id' => 'ID_Provincia']);
    }
    public function getLocalidades()
    {
        return $this->hasOne(Localidades::className(), ['id' => 'ID_Localidades']);
    }
    public function getSucursales()
    {
        return $this->hasOne(Sucursales::className(), ['id' => 'Sucursal']);
    }
    public function getName()
    {
        $destinatario = findOne(Destinatarios::className(), ['Cuit_Cuil' => 'destinatario']);
        return $destinatario->Nombre_RazonSocial;
    }
    
    public function count()
    {
      $cantidad = Destinatarios::find()->count();
      return  $cantidad;
    }
    

}

ban-car/controllers/DestinatariosController.php
<?php

namespace app\controllers;

use app\models\Localidades;
use Yii;
use app\models\Destinatarios;
use yii\filters\AccessControl;
use app\models\DestinatariosSearch;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\web\Response;
use app\models\Usuarios;
use app\components\RegistroMovimientos;
use yii\web\Request;

/**
 * DestinatariosController implements the CRUD actions for Destinatarios model.
 */
class DestinatariosController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return ['access' =>
            [
                'class' => AccessControl::className(),
                'only' => ['index', 'create', 'delete', 'update', 'view'],
                'rules' => [
                    [
                        'actions' => ['index', 'update', 'view', 'delete', 'create'],

                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Usuarios::isUserAdmin(Yii::$app->user->identity->id);
                        },
                    ],
                    [
                        'actions' => ['index', 'update', 'view', 'create','delete'],

                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Usuarios::isUserFirmante(Yii::$app->user->identity->id);
                        },
                    ],
                    [
                        'actions' => [ 'index', 'update', 'view', 'create','delete'],

                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {
                            return Usuarios::isUserOperador(Yii::$app->user->identity->id);
                        },
                    ],
                    [
                        'actions' => ['login'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Destinatarios models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DestinatariosSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        if (!Yii::$app->user->isGuest) {
            return $this->render('index', [
                'searchModel' => $searchModel,
                'dataProvider' => $dataProvider,
            ]);
        } else {
            return $this->redirect(['site/login']);
        }


    }

    /**
     * Displays a single Destinatarios model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        
        //GRABA REGISTRO EN AUDIT ---------------------------------------------------------------------------
        $vista = Destinatarios::find()->where("ID_DES=:ID_DES", [":ID_DES" => $id])->one();
        $nombre = $vista->Nombre_RazonSocial;

        $usuario = Usuarios::find()->where("IdUsuarios=:IdUsuarios", [":IdUsuarios" => Yii::$app->user->identity->id])->one();
        $legajo = $usuario->LegajoUs;
        $usuario_insert = $legajo;

        RegistroMovimientos::history($usuario_insert);
        RegistroMovimientos::registrarMovimiento($legajo, 'VISTA', 'DESTINATARIOS', 'Vista del destinatario: ' . $nombre);
        //----------------------------------------------------------------------------------------------------
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Destinatarios model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */

    public function actionCreate()
    {
        $model = new Destinatarios();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            //$model->updateAttributes(['tiempo_creacion' => date('d-M-Y H:i:s'),'ip_registrada'=>Yii::$app->request->userIP]);

            //GRABA REGISTRO EN AUDIT ---------------------------------------------------------------------------
            $nombre = Destinatarios::findOne(Yii::$app->request->get('id'))->Nombre_RazonSocial;

            $usuario = Usuarios::find()->where("IdUsuarios=:IdUsuarios", [":IdUsuarios" => Yii::$app->user->identity->id])->one();
            $legajo = $usuario->LegajoUs;
            $usuario_insert = $legajo;

            RegistroMovimientos::history($usuario_insert);
            RegistroMovimientos::registrarMovimiento($legajo, 'CREAR', 'DESTINATARIOS', 'Creacion del usuario: ' . $nombre);
            //----------------------------------------------------------------------------------------------------

            return $this->redirect(['view', 'id' => $model->ID_DES]);
        }

        if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $out = self::getLocalidades($parents[0]);

                return ['output' => $out, 'selected' => ' '];
            }
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Destinatarios model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        //$localidad = Destinatarios::find()->where(['ID_DES'=>$id])->one();
        //$bandera = 0; 
        $model->scenario =  Destinatarios::SCENARIO_UPDATE;        
        
        if ($model->load(Yii::$app->request->post())) {
           
            $model->ID_Localidad = self::getParam() == 0 ? Destinatarios::findOne($id)->ID_Localidad : Self::getParam();
          
            if ($model->save()) {
                           
                //GRABA REGISTRO EN AUDIT ---------------------------------------------------------------------------
                $nombre = Destinatarios::findOne(Yii::$app->request->get('id'))->Nombre_RazonSocial;

                $usuario = Usuarios::find()->where("IdUsuarios=:IdUsuarios", [":IdUsuarios" => Yii::$app->user->identity->id])->one();
                $legajo = $usuario->LegajoUs;
                $usuario_insert = $legajo;

                RegistroMovimientos::history($usuario_insert);
                RegistroMovimientos::registrarMovimiento($legajo, 'ACTUALIZAR', 'DESTINATARIOS', 'Actualizo el usuario: ' . $nombre . ' Cambió: ');

                //----------------------------------------------------------------------------------------------------

                 return $this->redirect(['view', 'id' => $model->ID_DES]);
        }
       }
       
         if (isset($_POST['depdrop_parents'])) {
            $parents = $_POST['depdrop_parents'];
            if ($parents != null) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $out = self::getLocalidades($parents[0]);

                return ['output' => $out, 'selected' => ' '];
            }
        }
        
        return $this->render('update', [
            'model' => $model,
        ]);
    }
    
    public function getParam() {
        $campos = json_encode(Yii::$app->request->getBodyParams());
        $c = explode(',', $campos);
        $campos2 = array_slice($c, 5); 
        $var =str_replace(array('}','"'), '', $campos2);
        $campos3 = implode(',', $var); 
        $var2 =str_replace(array('actualizar-button:', ',', ':', 'ID_Localidad'), '', $campos3);      
       
        return intval($var2);
    }
    /**
     * Deletes an existing Destinatarios model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        //GRABA REGISTRO EN AUDIT ---------------------------------------------------------------------------
        $borrar = Destinatarios::find()->where("ID_DES=:ID_DES", [":ID_DES" => $id])->one();
        $nombre = $borrar->Nombre_RazonSocial;

        $usuario = Usuarios::find()->where("IdUsuarios=:IdUsuarios", [":IdUsuarios" => Yii::$app->user->identity->id])->one();
        $legajo = $usuario->LegajoUs;
        $usuario_insert = $legajo;

        RegistroMovimientos::history($usuario_insert);
        RegistroMovimientos::registrarMovimiento($legajo, 'BORRAR', 'DESTINATARIOS', 'Borrar usuario: ' . $nombre);
        //----------------------------------------------------------------------------------------------------

        $this->findModel($id)->delete();


        return $this->redirect(['index']);
    }

    /**
     * Finds the Destinatarios model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Destinatarios the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Destinatarios::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }


    public function actionCarga()
    {
        $contador = 0;

ban-car/views/destinatarios/_form.php
<?php

use app\models\Provincias;
use kartik\depdrop\DepDrop;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\ActiveForm;
use app\models\Pais;
use yii\helpers\ArrayHelper;
use app\models\Localidades;
use app\models\Sucursales;

/* @var $this yii\web\View */
/* @var $model app\models\Destinatarios */
/* @var $form yii\widgets\ActiveForm */
?>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
<div class="destinatarios-form">
    <div class="col-md-8 col-lg-12">
        <?php $form = ActiveForm::begin([
            'enableAjaxValidation' => false, 
            'id' => 'destinatarios-form',
            'method' => 'post',
        ]);
        $dataProvincias = ArrayHelper::map(Provincias::find()->asArray()->orderBy('nombre')->all(), 'id', 'nombre');
        ?>

        <div class="align-items-center">
            <div class="form-group">
                 <div class="col-auto col-md-6">
                    <?= $form->field($model, 'DNI', ['options' => ['class' => 'no-margin']])->textInput(['disabled' => true]) ?>
                </div>
                <div class="col-auto col-md-6">
                    <?= $form->field($model, 'Tipo_documento', ['options' => ['class' => 'no-margin']])->textInput(['disabled' => true]) ?>
                </div>
            </div>
             <div class="form-group">
                <div class="col-auto col-md-6">
                    <?= $form->field($model, 'Nombre_RazonSocial', ['options' => ['class' => 'no-margin']])->textInput(['maxlength' => true, 'disabled'=>true]) ?>
                </div>
                <div class="col-auto col-md-6">
                    <?= $form->field($model, 'Cuit_Cuil', ['options' => ['class' => 'no-margin']])->textInput(['disabled' => true]) ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-6 col-md-4">
                <?= $form->field($model, 'Email', ['options' => ['class' => 'no-margin']])->textInput() ?>
            </div>
            <div class="col-lg-6 col-md-4">
                <?= $form->field($model, 'Direccion', ['options' => ['class' => 'no-margin']])->textInput() ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-3">
                <?= $form->field($model, 'Sucursal', ['options' => ['class' => 'no-margin']])->textInput(['value'=> Sucursales::findOne($model->Sucursal)->nombre, 'disabled'=>true])?>
            </div>
            <div class="col-lg-3">
                <?= $form->field($model, 'Cuenta', ['options' => ['class' => 'no-margin']])->textInput(['disabled' => true]) ?>
            </div>
             <div class="col-lg-2">
                <?= $form->field($model, 'Grupo', ['options' => ['class' => 'no-margin']])->textInput(['disabled' => true]) ?>
            </div>
             <div class="col-lg-2">
                <?= $form->field($model, 'Subgrupo', ['options' => ['class' => 'no-margin']])->textInput(['disabled' => true]) ?>
            </div>
             <div class="col-lg-2">
                <?= $form->field($model, 'Tipo_cuenta', ['options' => ['class' => 'no-margin']])->textInput(['disabled' => true]) ?>
            </div>
        </div>
        <div class="form-group">
            <div class="col-lg-4 col-md-4">
                <?= $form->field($model, 'Codigo_pais', ['options' => ['class' => 'no-margin']])->dropDownList(ArrayHelper::map(Pais::find()
                    ->all(), 'Cod_Pais', 'Nombre_Pais'))
                    ->label('Pais') ?>
            </div>
            <div class="col-lg-4 col-md-4">
                <?= $form->field($model, 'ID_Provincia', ['options' => ['class' => 'no-margin']])
                    ->dropDownList($dataProvincias, ['prompt' => 'Elija una provincia', 'id' => 'id_prov'])
                    ->label('Provincia'); ?>
            </div>

            <div class="col-lg-4 col-md-4">
                <?php if ($model->ID_Localidad>0){
                    $localidad = Localidades::find()->where("id=:id", [":id" => $model->ID_Localidad])->one();
                    echo $form->field($model, 'ID_Localidad')->widget(DepDrop::className(),
                        [
                            'data' => [$localidad->nombre],
                            'pluginOptions' => [
                                'placeholder' => 'Elija una localidad',
                                'depends' => ['id_prov'],
                                'url' => Url::to(['/destinatarios/create'])
                            ]
                        ]
                    )->label('Localidad'); 
                }else{
                 echo $form->field($model, 'ID_Localidad')->widget(DepDrop::className(),
                    [
                        'pluginOptions' => [
                            'placeholder' => 'Elija una localidad',
                            'depends' => ['id_prov'],
                            'url' => Url::to(['/destinatarios/create'])
                        ]
                    ]
                    )->label('Localidad');  
                } ?>
            </div>
        </div>
        <div class="col-lg-offset-2 col-lg-7">
           <?= Html::submitButton('Guardar', ['class' => 'btn bg-navy color-palette btn-block', 'name' => 'actualizar-button']) ?>
        </div>

        <?php ActiveForm::end(); ?>
    </div>
</div>

ban-car/views/destinatarios/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\destinatariosSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="destinatarios-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'ID_DES') ?>

    <?= $form->field($model, 'DNI') ?>

    <?= $form->field($model, 'Tipo_documento') ?>

    <?= $form->field($model, 'Cuit_Cuil') ?>

    <?= $form->field($model, 'Fecha_Nacimiento') ?>

    <?php // echo $form->field($model, 'Nombre_RazonSocial') ?>

    <?php // echo $form->field($model, 'Sexo') ?>

    <?php // echo $form->field($model, 'Ciudadania') ?>

    <?php // echo $form->field($model, 'Telefono') ?>

    <?php // echo $form->field($model, 'Celular') ?>

    <?php // echo $form->field($model, 'Cod_postal') ?>

    <?php // echo $form->field($model, 'Direccion') ?>

    <?php // echo $form->field($model, 'Email') ?>

    <?php // echo $form->field($model, 'Estado_civil') ?>

    <?php // echo $form->field($model, 'Cod_actividad') ?>

    <?php // echo $form->field($model, 'Sucursal') ?>

    <?php // echo $form->field($model, 'Cuenta') ?>

    <?php // echo $form->field($model, 'Grupo') ?>

    <?php // echo $form->field($model, 'Subgrupo') ?>

    <?php // echo $form->field($model, 'Tipo_cuenta') ?>

    <?php // echo $form->field($model, 'Codigo_pais') ?>

    <?php // echo $form->field($model, 'ID_Provincia') ?>

    <?php // echo $form->field($model, 'ID_Localidad') ?>

    <?php // echo $form->field($model, 'Tipo_domicilio') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

ban-car/views/destinatarios/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\destinatarios */

$this->title = 'Create Destinatarios';
$this->params['breadcrumbs'][] = ['label' => 'Destinatarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="destinatarios-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

ban-car/views/destinatarios/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel app\models\destinatariosSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = '';
$this->params['breadcrumbs'][] = ['label' => 'Destinatarios', 'url' => ['index']];;

?>
<link rel="stylesheet" type="text/css" href="../web/css/titulos.css">
<div class="destinatarios-index">

    <h1 id="titulo"><?php echo '<b>' . 'DESTINA' . '</b>' . 'TARIOS' ?></h1>

 
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            
            'Nombre_RazonSocial',
            'DNI',
            'Tipo_documento',
            'Cuit_Cuil',
 
            [
                'attribute' => 'Sucursal',
                'headerOptions' => ['style' => 'text-align: center;justify-content:center;'],
                'label' => 'Sucursal',
                'value' => 'sucursales.nombre'
            ],
            'Cuenta',
            'Grupo',
            'Subgrupo',
            'Tipo_cuenta',


            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>


</div>

ban-car/views/destinatarios/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Destinatarios */


$this->title = '';
$this->params['breadcrumbs'][] = ['label' => 'Destinatarios', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->Nombre_RazonSocial, 'url' => ['view', 'id' => $model->ID_DES]];
$this->params['breadcrumbs'][] = 'Actualizar';
?>
<link rel="stylesheet" type="text/css" href="../web/css/titulos.css">
<div class="destinatarios-index">
    

    <h1 id="titulo" style="text-align: center;">
        <?= '<b>' . 'ACTUA' . '</b>' . 'LIZAR' ?>
    </h1>
    
    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>