ban-car/models/Plantillas.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "plantillas".
 *
 * @property int $id
 * @property string $archivo
 * @property int $motivo_plantilla
 * @property string $nombre_archivo
 * @property int|null $sector
 * @property int|null $nombre
 * @property int|null $cuenta
 * @property int|null $cuil
 * @property int|null $sucursal
 * @property int|null $saldo
 * @property int|null $saldo_comision
 * @property int|null $fecha_emision
 * @property int|null $fecha_rechazo
 * @property int|null $fecha_inhabilitacion
 * @property int|null $fecha_cierre
 * @property int|null $motivo_cierre
 * @property int|null $cheque_diferido
 * @property int|null $cheque_comun
 * @property int|null $entidad
 * @property int|null $documentacion
 * @property int|null $cant_dias
 * @property int|null $saldo_letras
 * @property int|null $operacion
 * @property int|null $dias_letras
 * @property int|null $expediente
 * @property int|null $caratulado
 * @property int|null $letra
 * @property int|null $año_deuda
 * @property int|null $mes_deuda
 * @property int|null $cuotas
 * @property int|null $cuotas_vencidas
 * @property int|null $fecha_vencimiento
 * @property int|null $numero_multa
 * @property int|null $monto_garantia_letras
 * @property int|null $monto_garantia
 * @property int|null $tipo_garantia
 * @property int|null $motivo_rechazo
 * @property int|null $saldo_comision_letras
 * @property int|null $saldo_acreedor_letras
 * @property int|null $saldo_acreedor
 * @property int|null $saldo_deudor
 * @property int|null $saldo_deudor_letras
 * @property int|null $serie
 * @property int|null $a_favor
 * @property int|null $presentador
 * @property int|null $libradores
 * @property int|null $motivo
 * 
 * @property Motivo $motivoPlantilla
 */
class Plantillas extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'plantillas';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['archivo', 'motivo_plantilla', 'nombre_archivo'], 'required'],
            [['motivo_plantilla', 'sector', 'nombre', 'cuenta', 'cuil', 'sucursal', 'saldo', 'saldo_comision', 'fecha_emision', 'fecha_rechazo', 'fecha_inhabilitacion', 'fecha_cierre', 'motivo_cierre', 'cheque_diferido', 'cheque_comun', 'entidad', 'documentacion', 'cant_dias', 'saldo_letras', 'operacion', 'dias_letras', 'expediente', 'caratulado', 'letra', 'año_deuda', 'mes_deuda', 'cuotas', 'cuotas_vencidas', 'fecha_vencimiento', 'numero_multa', 'saldo_garantia_letras', 'saldo_garantia', 'tipo_garantia','motivo_rechazo', 'saldo_deudor',
                'saldo_acreedor','serie','libradores','presentador','a_favor','motivo'], 'integer'],
            [['archivo', 'nombre_archivo'], 'string', 'max' => 100],
            [['motivo_plantilla'], 'exist', 'skipOnError' => true, 'targetClass' => Motivo::className(), 'targetAttribute' => ['motivo_plantilla' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'archivo' => 'Archivo',
            'motivo_plantilla' => 'Motivo Plantilla',
            'nombre_archivo' => 'Nombre Archivo',
            'sector' => 'Sector',
            'nombre' => 'Nombre',
            'cuenta' => 'Cuenta',
            'cuil' => 'Cuil',
            'sucursal' => 'Sucursal',
            'saldo' => 'Saldo',
            'saldo_comision' => 'Saldo Comision',
            'fecha_emision' => 'Fecha Emision',
            'fecha_rechazo' => 'Fecha Rechazo',
            'fecha_inhabilitacion' => 'Fecha Inhabilitacion',
            'fecha_cierre' => 'Fecha Cierre',
            'motivo_cierre' => 'Motivo Cierre',
            'cheque_diferido' => 'Cheque Diferido',
            'cheque_comun' => 'Cheque Comun',
            'entidad' => 'Entidad',
            'documentacion' => 'Documentacion',
            'cant_dias' => 'Cant Dias',
            'saldo_letras' => 'Saldo Letras',
            'operacion' => 'Operacion',
            'dias_letras' => 'Dias Letras',
            'expediente' => 'Expediente',
            'caratulado' => 'Caratulado',
            'letra' => 'Letra',
            'año_deuda' => 'Año Deuda',
            'mes_deuda' => 'Mes Deuda',
            'cuotas' => 'Cuotas',
            'cuotas_vencidas' => 'Cuotas Vencidas',
            'fecha_vencimiento' => 'Fecha Vencimiento',
            'numero_multa' => 'Numero Multa',
            'saldo_garantia_letras' => 'Monto Garantia Letras',
            'saldo_garantia' => 'Saldo Garantia',
            'tipo_garantia' => 'Tipo Garantia',
            'motivo_rechazo' =>'Motivo de Rechazo',
            'saldo_comision' => 'Saldo Comision',
            'saldo_deudor' => 'Saldo Deudor',
            'saldo_deudor_letras' => 'Saldo Deudor Letras',
            'saldo_acreedor' => 'Saldo Acreedor',
            'saldo_acreedor_letras' => 'Saldo Acreedor Letras',
            'serie' => 'Serie',
            'libradores' => 'Librador/es',
            'presentador'=>'Presentador',
            'a_favor' =>'A favor de',
            'motivo' => 'Motivo',
        ];
    }

    /**
     * Gets query for [[MotivoPlantilla]].
     *
     * @return \yii\db\ActiveQuery
     */
    public function getMotivoPlantilla()
    {
        return $this->hasOne(Motivo::className(), ['id' => 'motivo_plantilla']);
    }
    public function getName()
    {
        return $this->nombre_archivo;
    }
    public function getSectores()
    {
        return $this->hasOne(Sectores::className(), ['ID_SECTORES' => 'sector']);
    }
    public function getMotivos()
    {
        return $this->hasOne(Motivo::className(), ['id' => 'motivo_plantilla']);
    }
    
}

ban-car/views/layouts/content.php
<?php
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo \yii\helpers\Html::encode($this->title);
                } else {
                    echo \yii\helpers\Inflector::camel2words(
                        \yii\helpers\Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Version</b> 2.0
    </div>
    <strong>Copyright &copy; 2021 <a href="http://bancorioja.com.ar">Banco Rioja S.A.U- BAN.CAR</a>.</strong> Todos los derechos reservados.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
        <li><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
        <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    
</aside><!-- /.control-sidebar -->
<!-- Add the sidebar's background. This div must be placed
     immediately after the control sidebar -->
<div class='control-sidebar-bg'></div>

ban-car/views/layouts/header.php
<?php

use yii\helpers\Html;
use app\models\Usuarios;
use app\models\Sectores as Sectores;
use yii\helpers\ArrayHelper;

/* @var $this \yii\web\View */
/* @var $content string */
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">BC</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <?php if (!Yii::$app->user->isGuest): ?>
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">

                        <span class="hidden-xs">Usuario activo: <?= Yii::$app->user->identity->usernameUs ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                              <?php echo Html::img('@web/img/BAN.CAR2.png', ['class' => 'img-circle']); ?>

                            <p class="user-header">
                                <strong>
                                    - <?= Yii::$app->user->identity->NombreUs . ' ' . Yii::$app->user->identity->ApellidoUs ?> </strong>
                                <span> - </br><?php if (Yii::$app->user->identity->IdSectores == null) {
                                        echo 'Sector sin definir';
                                    } else {
                                        echo Sectores::find()->where(['ID_SECTORES' => Yii::$app->user->identity->IdSectores])->one()->Sectores;
                                    } ?></br></span>
                                <small> Miembro desde: <?php
                                    echo Yii::$app->formatter->asDate(Yii::$app->user->identity->tiempo_creacion, 'long'); ?> </small>

                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <?= Html::a('Perfil', ['usuarios/profile', 'id' => Yii::$app->user->identity->IdUsuarios], ['class' => 'btn btn-default btn-flat']) ?>
                            </div>
                            <div class="pull-right">
                                <?= Html::a('Cerrar Sesion',['/site/logout','id'=>Yii::$app->user->identity->IdUsuarios],['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
<?php endif ?>
</header>

ban-car/views/layouts/left.php
<?php

use app\models\Usuarios;
use app\models\Sectores;
use yii\helpers\Html;

?>
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <?php echo Html::img('@web/img/BAN.CAR2.png', ['class' => 'img-circle user-image img-rounded img-responsive']); ?>
            </div>
            <div class="pull-left info">
                <p><?= Yii::$app->user->identity->NombreUs . ' ' . Yii::$app->user->identity->ApellidoUs ?> </p>


                <?php if (Yii::$app->user->identity->IdSectores == null) {
                    echo 'Sector sin definir';
                } else { ?>
                    <span> <?= Sectores::findOne(Yii::$app->user->identity->IdSectores)->Sectores ?> </span>
                <?php } ?>
            </div>
        </div>
        <?php
        $navItems = [1];
        if (Yii::$app->user->identity->IdRoles == Usuarios::ROLE_ADMIN) {
            array_shift($navItems);
            array_push($navItems,
                [

                    'label' => 'Cartas Documento',
                    'icon' => 'envelope',
                    'items' => [
                        [
                            'label' => 'Configurar',
                            'icon' => 'cog',
                            'url' => ['/cartas/configurar']
                        ],
                    ]
                ],
                [
                    'label' => 'Plantillas',
                    'icon' => 'list-alt',
                    'items' => [
                        [
                            'label' => 'Plantillas',
                            'icon' => 'tag',
                            'url' => ['/plantillas']
                        ],
                        [
                            'label' => 'Crear Plantilla',
                            'icon' => 'pencil',
                            'url' => ['/plantillas/create']
                        ],
                        [
                            'label' => 'Motivo de plantillas',
                            'icon' => 'bookmark',
                            'url' => ['/motivo']
                        ],
                    ],
                ],
                [
                    'label' => 'Destinatarios',
                    'icon' => 'font',
                    'url' => ['/destinatarios']
                ],
                [
                    'label' => 'Sectores',
                    'icon' => 'font',
                    'url' => ['/sectores']
                ],
                [
                    'label' => 'Usuarios',
                    'icon' => 'user',
                    'items' => [
                        [
                            'label' => 'Ver Usuarios',
                            'icon' => 'eye open',
                            'url' => ['/usuarios'],
                        ],
                        [
                            'label' => 'Crear Usuarios',
                            'icon' => 'pencil',
                            'url' => ['/usuarios/create']
                        ],
                        [
                            'label' => 'Auditoria',
                            'icon' => 'user',
                            'url' => ['/audit']
                        ],
                    ]
                ]);
        } elseif (Yii::$app->user->identity->IdRoles == Usuarios::ROLE_FIRMANTE) {
            array_shift($navItems);
            array_push($navItems,
                [

                    'label' => 'Cartas Documento',
                    'icon' => 'envelope',
                    'items' => [
                        [
                            'label' => 'Cartas Documento',
                            'icon' => 'tag',
                            'url' => ['/cartas']
                        ],
                        [
                            'label' => 'Crear Carta Documento',
                            'icon' => 'pencil',
                            'url' => ['/cartas/armar-plantilla']
                        ],
                        [
                            'label' => 'Pendiente de Autorizacion',
                            'icon' => 'hourglass',
                            'url' => ['/cartas/pending']
                        ],
                    ]
                ],
                [
                    'label' => 'Plantillas',
                    'icon' => 'list-alt',
                    'items' => [
                        [
                            'label' => 'Plantillas',
                            'icon' => 'tag',
                            'url' => ['/plantillas']
                        ],
                    ],
                ],
                [
                    'label' => 'Destinatarios',
                    'icon' => 'font',
                    'url' => ['/destinatarios']
                ]);
        } elseif (Yii::$app->user->identity->IdRoles == Usuarios::ROLE_OPERADOR) {
            array_shift($navItems);
            array_push($navItems,
                [

                    'label' => 'Cartas Documento',
                    'icon' => 'envelope',
                    'items' => [
                        [
                            'label' => 'Cartas Documento',
                            'icon' => 'tag',
                            'url' => ['/cartas']
                        ],
                        [
                            'label' => 'Crear Carta Documento',
                            'icon' => 'pencil',
                            'url' => ['/cartas/armar-plantilla']
                        ],
                        [
                            'label' => 'Pendiente de Revision',
                            'icon' => 'wrench',
                            'url' => ['/cartas/pending-revision']
                        ],
                        [
                            'label' => 'Pendiente de Despacho',
                            'icon' => 'send',
                            'url' => ['/cartas/pending-delivery']
                        ],
                    ]
                ],
                [

                    'label' => 'Plantillas',
                    'icon' => 'list-alt',
                    'items' => [
                        [
                            'label' => 'Plantillas',
                            'icon' => 'tag',
                            'url' => ['/plantillas']
                        ],
                    ],
                ],
                [
                    'label' => 'Destinatarios',
                    'icon' => 'font',
                    'url' => ['/destinatarios']
                ]);
        }

        ?>

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget' => 'tree'],
                'items' => $navItems,
            ]
        ) ?>

    </section>

</aside>

ban-car/views/layouts/main-login.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

ban-car/views/layouts/main.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */


    if (class_exists('backend\assets\AppAsset')) {
        backend\assets\AppAsset::register($this);
    } else {
        app\assets\AppAsset::register($this);
    }

    dmstr\web\AdminLteAsset::register($this);

    $directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
    ?>
    <?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>"/>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body class="hold-transition skin-purple sidebar-mini">
    <?php $this->beginBody() ?>
    <div class="wrapper">

        <?= $this->render(
            'header.php',
            ['directoryAsset' => $directoryAsset]
        ) ?>

        <?= $this->render(
            'left.php',
            ['directoryAsset' => $directoryAsset]
        )
        ?>

        <?= $this->render(
            'content.php',
            ['content' => $content, 'directoryAsset' => $directoryAsset]
        ) ?>

    </div>

    <?php $this->endBody() ?>
    </body>
    </html>
    <?php $this->endPage() ?>

ban-car/views/layouts/main1.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="es" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" /> -
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php //echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">
	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
		<?php $this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'Home', 'url'=>array('/site/index')),
				array('label'=>'About', 'url'=>array('/site/page', 'view'=>'about')),
				array('label'=>'Contact', 'url'=>array('/site/contact')),
				array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); ?>
	</div><!-- mainmenu -->

	<?php $this->widget('zii.widgets.CBreadcrumbs', array(
		'links'=>$this->breadcrumbs,
	)); ?><!-- breadcrumbs -->

	<?php echo $content; ?>

	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>